#!/bin/bash
cd `dirname $0`
pwd

echo API_APP_NAME: ${API_APP_NAME}
echo SOURCE_VERSION: ${SOURCE_VERSION}

if [ "${API_APP_NAME}" == "staging" ] ; then
    echo "build for Staging"
    ./build-staging
else
    echo "build for Production"
    ./build-production
fi